export {default as Home} from './Home/Home';
export {default as About} from './About/About'
export {default as Contact} from './contact/Contact'
export {default as VR} from './vr360/VR'
export {default as AR} from './AR/AR'
export {default as VRL} from './vr/VRL'
export {default as MR} from './mr/MR'
export {default as MAD} from './mad/MAD'
export {default as WDD} from './wdd/WDD'
export {default as RI} from './ri/RI';
export {default as Php }from './Technology/Php';
export {default as Laravel} from './Technology/Laravel';
export {default as CodeIngenator} from './Technology/CodeIngenator';
export  {default as Python} from './Technology/Python';
export  {default as Node} from './Technology/Node';
export {default as  Angular} from './Technology/Angular';
export  {default as Reactjs} from './Technology/Reactjs';
export  {default as Vue }from './Technology/Vue';
export  {default as Mean} from './Technology/Mean';
export  {default as Mern} from './Technology/Mern';
export  {default as Magento} from './Technology/Magento';
export  {default as WooCommerce} from './Technology/WooCommerce';
export  {default as Shopify} from './Technology/Shopify';
export  {default as IOS} from './Technology/IOS';
export  {default as Android} from './Technology/Android';
export  {default as ReactNative} from './Technology/ReactNative';
export  {default as Hybrid} from './Technology/Hybrid';
export  {default as Flutter }from './Technology/Flutter';
export  {default as Ionic} from './Technology/Ionic';
export  {default as Swift} from './Technology/Swift';
export  {default as Worldpress} from './Technology/Worldpress';
export  {default as Drupal} from './Technology/Drupal';
export  {default as CustomUnrealEngine} from './Technology/CustomUnrealEngine';
export  {default as UnityAppDevelopment} from './Technology/UnityAppDevelopment';
export  {default as Technology} from './Technology/Technology';
export  {default as Projects} from './projects/Projects';
export  {default as Project1} from './projects/Project1';
export  {default as Project2} from './projects/Project2';